// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOeDDLC4MComMlArnwzaUJSFMPwIh3LlU',
    appId: '1:1073423015869:web:c3023b32c2b0988372bcd4',
    messagingSenderId: '1073423015869',
    projectId: 'xeroxshop-college-app-e4182',
    authDomain: 'xeroxshop-college-app-e4182.firebaseapp.com',
    storageBucket: 'xeroxshop-college-app-e4182.firebasestorage.app',
    measurementId: 'G-N5TK62PCG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxfaHVwt9lwrdgkRHVIzTPvLOoVJj7W4A',
    appId: '1:1073423015869:android:d022aebfb14c3b4672bcd4',
    messagingSenderId: '1073423015869',
    projectId: 'xeroxshop-college-app-e4182',
    storageBucket: 'xeroxshop-college-app-e4182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVRA_qAzqYJhNzPY8XJVXpswlaGR77Pw',
    appId: '1:1073423015869:ios:7e4dcb159a46250172bcd4',
    messagingSenderId: '1073423015869',
    projectId: 'xeroxshop-college-app-e4182',
    storageBucket: 'xeroxshop-college-app-e4182.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHVRA_qAzqYJhNzPY8XJVXpswlaGR77Pw',
    appId: '1:1073423015869:ios:7e4dcb159a46250172bcd4',
    messagingSenderId: '1073423015869',
    projectId: 'xeroxshop-college-app-e4182',
    storageBucket: 'xeroxshop-college-app-e4182.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOeDDLC4MComMlArnwzaUJSFMPwIh3LlU',
    appId: '1:1073423015869:web:8160ab38840e73ee72bcd4',
    messagingSenderId: '1073423015869',
    projectId: 'xeroxshop-college-app-e4182',
    authDomain: 'xeroxshop-college-app-e4182.firebaseapp.com',
    storageBucket: 'xeroxshop-college-app-e4182.firebasestorage.app',
    measurementId: 'G-NEYD5YP983',
  );
}
